### ISSUE TITLE
Strange problem with sensors

### ISSUE THREAD

**Issue by Xstoudi** [WasabiFan/ev3dev-lang-js#6] opened 2016-01-15 15:39 UTC
There is a strange problem with sensors. Most of time, it crashs when trying to create a new Sensor instance.

Here is the crash log:

```
/home/robot/Main.js:37
    var ultrasonicSensor = new ev3dev.UltrasonicSensor(ev3dev.INPUT_4);
                           ^
TypeError: undefined is not a function
    at Socket.<anonymous> (/home/robot/Main.js:37:28)
    at Socket.Emitter.emit (/home/robot/node_modules/component-emitter/index.js:131:20)
    at Socket.onevent (/home/robot/node_modules/socket.io-client/lib/socket.js:263:10)
    at Socket.onpacket (/home/robot/node_modules/socket.io-client/lib/socket.js:221:12)
    at Manager.<anonymous> (/home/robot/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/robot/node_modules/component-emitter/index.js:131:20)
    at Manager.ondecoded (/home/robot/node_modules/socket.io-client/lib/manager.js:333:8)
    at Decoder.<anonymous> (/home/robot/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/home/robot/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/robot/node_modules/socket.io-parser/index.js:247:12)
```

Knowing that `ev3dev` is declared like `var ev3dev = require("ev3dev-lang");`

**Comment by WasabiFan** [comment] 2016-01-15 15:58
I'm sure I tested this before I released :confused: I'll take a look later today. It's probably something that I did wrong.

Thanks for reporting!

**Comment by WasabiFan** [comment] 2016-01-15 16:11
I know what the issue is... my mistake. I didn't update the export file after my most recent changes so that it actually exported the special sensor classes. I'll publish a fix in a few hours.

For now, you should be able to do this for your import (I haven't tested this, but I expect it should work as a workaround):

``` js
var ev3dev  = require('ev3dev-lang');
var ev3devSensors = require('ev3dev-lang/bin/sensors.js');
ev3dev.UltrasonicSensor = ev3devSensors.UltrasonicSensor;
```

**Comment by WasabiFan** [comment] 2016-01-16 03:00
This should be fixed in `v0.9.4`. Please update and confirm that the issue has been resolved.

**Comment by Xstoudi** [comment] 2016-01-18 07:25
It's working well !

**Comment by Xstoudi** [comment] 2016-01-18 08:03
Can you confirm the "GYRO-ANG" mode is working properly ?

**Comment by WasabiFan** [comment] 2016-01-18 08:13
Please open a new issue, as this is a separate problem. If you're asking about this JavaScript library in particular (the issue is that you are getting JavaScript errors or there is a variable that is missing) open it on this repo; otherwise, please open it on the main ev3dev repo. Doing it this way makes it much easier to keep track of remaining work items.

Thanks!

**Closed as completed** 2016-01-18 16:19 UTC
